name: Linux VPS Setup

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y wget unzip openssh-server

    - name: Download Ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract Ngrok
      run: unzip ngrok.zip

    - name: Authenticate Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable SSH Server
      run: sudo systemctl start ssh && sudo systemctl enable ssh

    - name: Set Default Password (Auto)
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Allow SSH Login
      run: sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && sudo systemctl restart ssh

    - name: Create SSH Tunnel with Ngrok
      run: ./ngrok tcp 22 
